billions:
  main:
    contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
    networkURL: https://rpc-mainnet.billions.network
  test:
    contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
    networkURL: http://billions-testnet-rpc.eu-north-2.gateway.fm
