name: Push matrixdotorg/sygnal to AWS PrivadoID environment

on:
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PRIVADO_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_PRIVADO_ID }}
  ECR_REPOSITORY: notification_service_sygnal
  MATRIX_SYGNAL_REPOSITORY: matrixdotorg/sygnal
  MATRIX_SYGNAL_VERSION: v0.15.0

jobs:
  deploy:
    environment:
      name: ${{ github.ref_name }}
    name: Push matrixdotorg/sygnal to AWS account
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/PolygonIDActionsRole
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Pull and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        run: |
          docker pull ${{ env.MATRIX_SYGNAL_REPOSITORY }}:${{ env.MATRIX_SYGNAL_VERSION }}
          docker tag  ${{ env.MATRIX_SYGNAL_REPOSITORY }}:${{ env.MATRIX_SYGNAL_VERSION }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.MATRIX_SYGNAL_VERSION }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.MATRIX_SYGNAL_VERSION }}
