name: Deploy notification service on AWS PrivadoID Environment

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PRIVADO_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_PRIVADO_ID }}
  ECR_REPOSITORY: notification_service

jobs:
  deploy:
    environment:
      name: ${{ github.ref_name }}
    name: Build and deploy notification service to AWS account
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/PolygonIDActionsRole
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Get version
        run: echo "::set-output name=VERSION::$(git rev-parse --short HEAD)"
        id: version

      - name: Get tag
        run: |
          if [ "${{ github.ref_name }}" == "develop" ]; then
            echo "::set-output name=DOCKER_TAG::develop"
          else
            echo "::set-output name=DOCKER_TAG::latest"
          fi
        id: tag

      - name: Build with tag and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          VERSION_TAG: ${{ steps.version.outputs.VERSION }}
          IMAGE_TAG: ${{ steps.tag.outputs.DOCKER_TAG }}
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.VERSION_TAG }} .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.VERSION_TAG }}

          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
